// node-opcua simple server
exports.nodes_node_opcua = {
    scalar_boolean: "ns=411;s=Scalar_Static_Boolean",
    scalar_sbyte: "ns=411;s=Scalar_Static_SByte",
    scalar_int16: "ns=411;s=Scalar_Static_Int16",
    scalar_int32: "ns=411;s=Scalar_Static_Int32",
    scalar_int64: "ns=411;s=Scalar_Static_Int64",
    scalar_byte: "ns=411;s=Scalar_Static_Byte",
    scalar_uint16: "ns=411;s=Scalar_Static_UInt16",
    scalar_uint32: "ns=411;s=Scalar_Static_UInt32",
    scalar_uint64: "ns=411;s=Scalar_Static_UInt64",
    scalar_float: "ns=411;s=Scalar_Static_Float",
    scalar_double: "ns=411;s=Scalar_Static_Double",
    scalar_string: "ns=411;s=Scalar_Static_String",
    scalar_datetime: "ns=411;s=Scalar_Static_DateTime",
    scalar_guid: "ns=411;s=Scalar_Static_Guid",
    scalar_bytestring: "ns=411;s=Scalar_Static_ByteString",
    scalar_xmlelement: "ns=411;s=Scalar_Static_XmlElement",
    scalar_localizedtext: "ns=411;s=Scalar_Static_LocalizedText",
    scalar_qualifiedname: "ns=411;s=Scalar_Static_QualifiedName",

    array_boolean: "ns=411;s=Scalar_Static_Array_Boolean",
    array_sbyte: "ns=411;s=Scalar_Static_Array_SByte",
    array_int16: "ns=411;s=Scalar_Static_Array_Int16",
    array_int32: "ns=411;s=Scalar_Static_Array_Int32",
    array_int64: "ns=411;s=Scalar_Static_Array_Int64",
    array_byte: "ns=411;s=Scalar_Static_Array_Byte",
    array_uint16: "ns=411;s=Scalar_Static_Array_UInt16",
    array_uint32: "ns=411;s=Scalar_Static_Array_UInt32",
    array_uint64: "ns=411;s=Scalar_Static_Array_UInt64",
    array_float: "ns=411;s=Scalar_Static_Array_Float",
    array_double: "ns=411;s=Scalar_Static_Array_Double",
    array_string: "ns=411;s=Scalar_Static_Array_String",
    array_datetime: "ns=411;s=Scalar_Static_Array_DateTime",
    array_guid: "ns=411;s=Scalar_Static_Array_Guid",
    array_bytestring: "ns=411;s=Scalar_Static_Array_ByteString",
    array_xmlelement: "ns=411;s=Scalar_Static_Array_XmlElement",
    array_localizedtext: "ns=411;s=Scalar_Static_Array_LocalizedText",
    array_qualifiedname: "ns=411;s=Scalar_Static_Array_QualifiedName",
};

exports.nodes_prosys = {
    scalar_boolean: "ns=3;s=Boolean",
    scalar_sbyte: "ns=3;s=SByte",
    scalar_int16: "ns=3;s=Int16",
    scalar_int32: "ns=3;s=Int32",
    scalar_int64: "ns=3;s=Int64",
    scalar_byte: "ns=3;s=Byte",
    scalar_uint16: "ns=3;s=UInt16",
    scalar_uint32: "ns=3;s=UInt32",
    scalar_uint64: "ns=3;s=UInt64",
    scalar_float: "ns=3;s=Float",
    scalar_double: "ns=3;s=Double",
    scalar_string: "ns=3;s=String",
    scalar_datetime: "ns=3;s=DateTime",
    scalar_guid: "ns=3;s=GUID",
    scalar_bytestring: "ns=3;s=ByteString",
    scalar_xmlelement: "ns=3;s=XmlElement",
    scalar_localizedtext: "ns=3;s=LocalizedText",
    scalar_qualifiedname: "ns=3;s=QualifiedName",

    array_boolean: "ns=3;s=BooleanArray",
    array_sbyte: "ns=3;s=SByteArray",
    array_int16: "ns=3;s=Int16Array",
    array_int32: "ns=3;s=Int32Array",
    array_int64: "ns=3;s=Int64Array",
    array_byte: "ns=3;s=ByteArray",
    array_uint16: "ns=3;s=UInt16Array",
    array_uint32: "ns=3;s=UInt32Array",
    array_uint64: "ns=3;s=UInt64Array",
    array_float: "ns=3;s=FloatArray",
    array_double: "ns=3;s=DoubleArray",
    array_string: "ns=3;s=StringArray",
    array_datetime: "ns=3;s=DateTimeArray",
    array_guid: "ns=3;s=GUIDArrayArray",
    array_bytestring: "ns=3;s=ByteStringArray",
    array_xmlelement: "ns=3;s=XmlElementArray",
    array_localizedtext: "ns=3;s=LocalizedTextArray",
    array_qualifiedname: "ns=3;s=QualifiedNameArray",
};

exports.nodes_uaautomation_cpp = {
    scalar_boolean: "ns=2;s=Demo.Static.Scalar.Boolean",
    scalar_sbyte: "ns=2;s=Demo.Static.Scalar.SByte",
    scalar_int16: "ns=2;s=Demo.Static.Scalar.Int16",
    scalar_int32: "ns=2;s=Demo.Static.Scalar.Int32",
    scalar_int64: "ns=2;s=Demo.Static.Scalar.Int64",
    scalar_byte: "ns=2;s=Demo.Static.Scalar.Byte",
    scalar_uint16: "ns=2;s=Demo.Static.Scalar.UInt16",
    scalar_uint32: "ns=2;s=Demo.Static.Scalar.UInt32",
    scalar_uint64: "ns=2;s=Demo.Static.Scalar.UInt64",
    scalar_float: "ns=2;s=Demo.Static.Scalar.Float",
    scalar_double: "ns=2;s=Demo.Static.Scalar.Double",
    scalar_string: "ns=2;s=Demo.Static.Scalar.String",
    scalar_datetime: "ns=2;s=Demo.Static.Scalar.DateTime",
    scalar_guid: "ns=2;s=Demo.Static.Scalar.Guid",
    scalar_bytestring: "ns=2;s=Demo.Static.Scalar.ByteString",
    scalar_xmlelement: "ns=2;s=Demo.Static.Scalar.XmlElement",
    scalar_localizedtext: "ns=2;s=Demo.Static.Scalar.LocalizedText",
    scalar_qualifiedname: "ns=2;s=Demo.Static.Scalar.QualifiedName",

    array_boolean: "ns=2;s=Demo.Static.Arrays.Boolean",
    array_sbyte: "ns=2;s=Demo.Static.Arrays.SByte",
    array_int16: "ns=2;s=Demo.Static.Arrays.Int16",
    array_int32: "ns=2;s=Demo.Static.Arrays.Int32",
    array_int64: "ns=2;s=Demo.Static.Arrays.Int64",
    array_byte: "ns=2;s=Demo.Static.Arrays.Byte",
    array_uint16: "ns=2;s=Demo.Static.Arrays.UInt16",
    array_uint32: "ns=2;s=Demo.Static.Arrays.UInt32",
    array_uint64: "ns=2;s=Demo.Static.Arrays.UInt64",
    array_float: "ns=2;s=Demo.Static.Arrays.Float",
    array_double: "ns=2;s=Demo.Static.Arrays.Double",
    array_string: "ns=2;s=Demo.Static.Arrays.String",
    array_datetime: "ns=2;s=Demo.Static.Arrays.DateTime",
    array_guid: "ns=2;s=Demo.Static.Arrays.Guid",
    array_bytestring: "ns=2;s=Demo.Static.Arrays.ByteString",
    array_xmlelement: "ns=2;s=Demo.Static.Arrays.XmlElement",
    array_localizedtext: "ns=2;s=Demo.Static.Arrays.LocalizedText",
    array_qualifiedname: "ns=2;s=Demo.Static.Arrays.QualifiedName",
};
exports.nodes_uaautomation_ansiC = {
    scalar_boolean: "ns=4;s=Demo.Static.Scalar.Boolean",
    scalar_sbyte: "ns=4;s=Demo.Static.Scalar.SByte",
    scalar_int16: "ns=4;s=Demo.Static.Scalar.Int16",
    scalar_int32: "ns=4;s=Demo.Static.Scalar.Int32",
    scalar_int64: "ns=4;s=Demo.Static.Scalar.Int64",
    scalar_byte: "ns=4;s=Demo.Static.Scalar.Byte",
    scalar_uint16: "ns=4;s=Demo.Static.Scalar.UInt16",
    scalar_uint32: "ns=4;s=Demo.Static.Scalar.UInt32",
    scalar_uint64: "ns=4;s=Demo.Static.Scalar.UInt64",
    scalar_float: "ns=4;s=Demo.Static.Scalar.Float",
    scalar_double: "ns=4;s=Demo.Static.Scalar.Double",
    scalar_string: "ns=4;s=Demo.Static.Scalar.String",
    scalar_datetime: "ns=4;s=Demo.Static.Scalar.DateTime",
    scalar_guid: "ns=4;s=Demo.Static.Scalar.Guid",
    scalar_bytestring: "ns=4;s=Demo.Static.Scalar.ByteString",
    scalar_xmlelement: "ns=4;s=Demo.Static.Scalar.XmlElement",
    scalar_localizedtext: "ns=4;s=Demo.Static.Scalar.LocalizedText",
    scalar_qualifiedname: "ns=4;s=Demo.Static.Scalar.QualifiedName",

    array_boolean: "ns=4;s=Demo.Static.Arrays.Boolean",
    array_sbyte: "ns=4;s=Demo.Static.Arrays.SByte",
    array_int16: "ns=4;s=Demo.Static.Arrays.Int16",
    array_int32: "ns=4;s=Demo.Static.Arrays.Int32",
    array_int64: "ns=4;s=Demo.Static.Arrays.Int64",
    array_byte: "ns=4;s=Demo.Static.Arrays.Byte",
    array_uint16: "ns=4;s=Demo.Static.Arrays.UInt16",
    array_uint32: "ns=4;s=Demo.Static.Arrays.UInt32",
    array_uint64: "ns=4;s=Demo.Static.Arrays.UInt64",
    array_float: "ns=4;s=Demo.Static.Arrays.Float",
    array_double: "ns=4;s=Demo.Static.Arrays.Double",
    array_string: "ns=4;s=Demo.Static.Arrays.String",
    array_datetime: "ns=4;s=Demo.Static.Arrays.DateTime",
    array_guid: "ns=4;s=Demo.Static.Arrays.Guid",
    array_bytestring: "ns=4;s=Demo.Static.Arrays.ByteString",
    array_xmlelement: "ns=4;s=Demo.Static.Arrays.XmlElement",
    array_localizedtext: "ns=4;s=Demo.Static.Arrays.LocalizedText",
    array_qualifiedname: "ns=4;s=Demo.Static.Arrays.QualifiedName",
};
exports.nodes_milo = {
    scalar_boolean: "ns=2;s=HelloWorld/ScalarTypes/Boolean",
    scalar_sbyte: "ns=2;s=HelloWorld/ScalarTypes/SByte",
    scalar_int16: "ns=2;s=HelloWorld/ScalarTypes/Int16",
    scalar_int32: "ns=2;s=HelloWorld/ScalarTypes/Int32",
    scalar_int64: "ns=2;s=HelloWorld/ScalarTypes/Int64",
    scalar_byte: "ns=2;s=HelloWorld/ScalarTypes/Byte",
    scalar_uint16: "ns=2;s=HelloWorld/ScalarTypes/UInt16",
    scalar_uint32: "ns=2;s=HelloWorld/ScalarTypes/UInt32",
    scalar_uint64: "ns=2;s=HelloWorld/ScalarTypes/UInt64",
    scalar_float: "ns=2;s=HelloWorld/ScalarTypes/Float",
    scalar_double: "ns=2;s=HelloWorld/ScalarTypes/Double",
    scalar_string: "ns=2;s=HelloWorld/ScalarTypes/String",
    scalar_datetime: "ns=2;s=HelloWorld/ScalarTypes/DateTime",
    scalar_guid: "ns=2;s=HelloWorld/ScalarTypes/Guid",
    scalar_bytestring: "ns=2;s=HelloWorld/ScalarTypes/ByteString",
    scalar_xmlelement: "ns=2;s=HelloWorld/ScalarTypes/XmlElement",
    scalar_localizedtext: "ns=2;s=HelloWorld/ScalarTypes/LocalizedText",
    scalar_qualifiedname: "ns=2;s=HelloWorld/ScalarTypes/QualifiedName",

    array_boolean: "ns=2;s=HelloWorld/ArrayTypes/BooleanArray",
    array_sbyte: "ns=2;s=HelloWorld/ArrayTypes/SByteArray",
    array_int16: "ns=2;s=HelloWorld/ArrayTypes/Int16Array",
    array_int32: "ns=2;s=HelloWorld/ArrayTypes/Int32Array",
    array_int64: "ns=2;s=HelloWorld/ArrayTypes/Int64Array",
    array_byte: "ns=2;s=HelloWorld/ArrayTypes/ByteArray",
    array_uint16: "ns=2;s=HelloWorld/ArrayTypes/UInt16Array",
    array_uint32: "ns=2;s=HelloWorld/ArrayTypes/UInt32Array",
    array_uint64: "ns=2;s=HelloWorld/ArrayTypes/UInt64Array",
    array_float: "ns=2;s=HelloWorld/ArrayTypes/FloatArray",
    array_double: "ns=2;s=HelloWorld/ArrayTypes/DoubleArray",
    array_string: "ns=2;s=HelloWorld/ArrayTypes/StringArray",
    array_datetime: "ns=2;s=HelloWorld/ArrayTypes/DateTimeArray",
    array_guid: "ns=2;s=HelloWorld/ArrayTypes/GuidArray",
    array_bytestring: "ns=2;s=HelloWorld/ArrayTypes/ByteStringArray",
    array_xmlelement: "ns=2;s=HelloWorld/ArrayTypes/XmlElementArray",
    array_localizedtext: "ns=2;s=HelloWorld/ArrayTypes/LocalizedTextArray",
    array_qualifiedname: "ns=2;s=HelloWorld/ArrayTypes/QualifiedNameArray"

};
exports.generic_opc = {
    scalar_boolean: "ns=2;s=DataAccess_DataItem_Boolean",
    scalar_sbyte: "ns=2;s=DataAccess_DataItem_SByte",
    scalar_int16: "ns=2;s=DataAccess_DataItem_Int16",
    scalar_int32: "ns=2;s=DataAccess_DataItem_Int32",
    scalar_int64: "ns=2;s=DataAccess_DataItem_Int64",
    scalar_byte: "ns=2;s=DataAccess_DataItem_Byte",
    scalar_uint16: "ns=2;s=DataAccess_DataItem_UInt16",
    scalar_uint32: "ns=2;s=DataAccess_DataItem_UInt32",
    scalar_uint64: "ns=2;s=DataAccess_DataItem_UInt64",
    scalar_float: "ns=2;s=DataAccess_DataItem_Float",
    scalar_double: "ns=2;s=DataAccess_DataItem_Double",
    scalar_string: "ns=2;s=DataAccess_DataItem_String",
    scalar_datetime: "ns=2;s=DataAccess_DataItem_DateTime",
    scalar_guid: "ns=2;s=DataAccess_DataItem_Guid",
    scalar_bytestring: "ns=2;s=DataAccess_DataItem_ByteString",
    scalar_xmlelement: "ns=2;s=DataAccess_DataItem_XmlElement",
    scalar_localizedtext: "ns=2;s=DataAccess_DataItem_LocalizedText",
    scalar_qualifiedname: "ns=2;s=DataAccess_DataItem_QualifiedName",

    array_boolean: "ns=2;s=DataAccess_AnalogType_Array_Boolean",
    array_sbyte: "ns=2;s=DataAccess_AnalogType_Array_SByte",
    array_int16: "ns=2;s=DataAccess_AnalogType_Array_Int16",
    array_int32: "ns=2;s=DataAccess_AnalogType_Array_Int32",
    array_int64: "ns=2;s=DataAccess_AnalogType_Array_Int64",
    array_byte: "ns=2;s=DataAccess_AnalogType_Array_Byte",
    array_uint16: "ns=2;s=DataAccess_AnalogType_Array_UInt16",
    array_uint32: "ns=2;s=DataAccess_AnalogType_Array_UInt32",
    array_uint64: "ns=2;s=DataAccess_AnalogType_Array_UInt64",
    array_float: "ns=2;s=DataAccess_AnalogType_Array_Float",
    array_double: "ns=2;s=DataAccess_AnalogType_Array_Double",
    array_string: "ns=2;s=DataAccess_AnalogType_Array_String",
    array_datetime: "ns=2;s=DataAccess_AnalogType_Array_DateTime",
    array_guid: "ns=2;s=DataAccess_AnalogType_Array_Guid",
    array_bytestring: "ns=2;s=DataAccess_AnalogType_Array_ByteString",
    array_xmlelement: "ns=2;s=DataAccess_AnalogType_Array_XmlElement",
    array_localizedtext: "ns=2;s=DataAccess_AnalogType_Array_LocalizedText",
    array_qualifiedname: "ns=2;s=DataAccess_AnalogType_Array_QualifiedName"
};

exports.nodes_openopcua = {

    scalar_boolean:       "ns=2;i=4",
    scalar_sbyte:         "ns=2;i=14",
    scalar_int16:         "ns=2;i=11",
    scalar_int32:         "ns=2;i=12",
    scalar_int64:         "ns=2;i=13",
    scalar_byte:          "ns=2;i=5",
    scalar_uint16:        "ns=2;i=16",
    scalar_uint32:        "ns=2;i=17",

    scalar_uint64:        "ns=2;i=18",
    scalar_float:         "ns=2;i=9",
    scalar_double:        "ns=2;i=8",
    scalar_string:        "ns=2;i=15",
    scalar_datetime:      "ns=2;i=7",
    scalar_guid:          "ns=2;i=10",
    scalar_bytestring:    "ns=2;i=6",
    scalar_xmlelement:    "ns=2;i=19",
    scalar_localizedtext: "ns=2;i=28",
    scalar_qualifiedname: "ns=2;i=27",
    /*
    array_boolean: "ns=411;s=Scalar_Static_Array_Boolean",
    array_sbyte: "ns=411;s=Scalar_Static_Array_SByte",
    array_int16: "ns=411;s=Scalar_Static_Array_Int16",
    array_int32: "ns=411;s=Scalar_Static_Array_Int32",
    array_int64: "ns=411;s=Scalar_Static_Array_Int64",
    array_byte: "ns=411;s=Scalar_Static_Array_Byte",
    array_uint16: "ns=411;s=Scalar_Static_Array_UInt16",
    array_uint32: "ns=411;s=Scalar_Static_Array_UInt32",
    array_uint64: "ns=411;s=Scalar_Static_Array_UInt64",
    array_float: "ns=411;s=Scalar_Static_Array_Float",
    array_double: "ns=411;s=Scalar_Static_Array_Double",
    array_string: "ns=411;s=Scalar_Static_Array_String",
    array_datetime: "ns=411;s=Scalar_Static_Array_DateTime",
    array_guid: "ns=411;s=Scalar_Static_Array_Guid",
    array_bytestring: "ns=411;s=Scalar_Static_Array_ByteString",
    array_xmlelement: "ns=411;s=Scalar_Static_Array_XmlElement",
    array_localizedtext: "ns=411;s=Scalar_Static_Array_LocalizedText",
    array_qualifiedname: "ns=411;s=Scalar_Static_Array_QualifiedName",
  */
};
